# generated by datamodel-codegen:
#   filename:  theme-schema.json

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import BaseModel


class Fonts(BaseModel):
    font: str
    fontSize: int
    fontBold: str
    fontItalic: Optional[str] = None
    fontName: str
    fontBoldName: str
    fontItalicName: Optional[str] = None
    fontFamily: str
    fontColor: str
    titleFontSize: int


class Paragraph(BaseModel):
    name: str
    spaceAfter: float


class Page(BaseModel):
    height: int
    width: float
    margin: List[Union[float, float, float, float]]
    pageSize: str
    styles: str


class TableStyles(BaseModel):
    valign: str
    align: str
    colWidths: List[Union[float, float]]


class Ordering(BaseModel):
    body: List[Union[str, str, str, str, str, str, str, str]]


class Head(BaseModel):
    leftTop: Union[bool, str]
    leftBot: Union[bool, str]
    rightTop: Union[bool, str]
    centerBot: Union[bool, str]
    centerTop: Union[bool, str]
    rightBot: Union[bool, str]
    center2Bot: Union[bool, str]


class HeadAln(BaseModel):
    leftTop: List[Union[float, float]]
    leftBot: List[Union[float, float]]
    rightTop: List[Union[float, float]]
    centerBot: List[Union[float, float]]
    centerTop: List[Union[float, float]]
    rightBot: List[Union[float, float]]
    center2Bot: List[Union[float, float]]


class HeadTitle(BaseModel):
    leftTop: bool
    leftBot: bool
    rightTop: bool
    centerBot: bool
    centerTop: bool
    rightBot: bool
    center2Bot: bool


class ThemeModel(BaseModel):
    fonts: Fonts
    paragraph: Paragraph
    page: Page
    tableStyles: TableStyles
    ordering: Ordering
    head: Head
    headAln: HeadAln
    headTitle: HeadTitle
    headLine: List[Union[float, float, float, float]]
    multiCol: bool
    nerd: bool
