name: frontend-deploy
on: [push, pull_request]
jobs:
  # test:
  #   ...
  deploy:
    name: "Deploy to frontend instance"
    runs-on: self-hosted
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    # needs: test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging2.key
          chmod 600 ~/.ssh/staging2.key
          cat >>~/.ssh/config <<END
          Host frontend
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging2.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.FRONTEND_DEPLOY_USER }}
          SSH_KEY: ${{ secrets.FRONTEND_DEPLOY_KEY }}
          SSH_HOST: ${{ secrets.FRONTEND_DEPLOY_HOST }}

      - name: Stop the server
        run: ssh frontend 'sudo systemctl stop nginx'

      - name: Everything
        run: ssh frontend 'cd ~/studentresume-web/frontend/ && git fetch && git reset --hard origin/main && npm i && rm -r build/ && npm run build && sudo scp -r ./build/* /var/www/build/'
      
      - name: Start the server
        if: ${{ always() }}
        run: ssh frontend 'sudo systemctl start nginx'